services:
  server:
    container_name: omnigate-server
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    environment:
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - DEFAULT_ORG_ID=${DEFAULT_ORG_ID}
      - DATABASE_URL=${DATABASE_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_SPACES_ENDPOINT=${S3_SPACES_ENDPOINT}
      - S3_SPACES_SECRET_KEY=${S3_SPACES_SECRET_KEY}
      - S3_SPACES_ACCESS_KEY_ID=${S3_SPACES_ACCESS_KEY_ID}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - NODE_ENV=production
      - IS_DOCKER=true
  web:
    container_name: omnigate-web
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    environment:
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - IS_DOCKER=true
  nginx:
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - web
