packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  '@types/node': ^22
  '@types/eslint': ^8
  zod: ^3.24.2
  react-hook-form: ^7.54.2
  '@hookform/resolvers': ^4.1.0
  dayjs: ^1.11.13
  hono: ^4.6.10
  '@icons-pack/react-simple-icons': ^10.2.0

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19.0.10
    '@types/react-dom': ^19.0.4
